language: java

matrix:
  include:
    - os: linux
      dist: trusty
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8.3

install: true
script: ./gradlew -u -i -S assemble

cache:
  directories:
    - $HOME/.gradle/
